function sce__f90(node, onCompleteCallback)
{
   var myobj = { label: "sce_main", id: "sce_main", href: "sce_main.html", target:"basefrm" };
   var tmpNode16 = new YAHOO.widget.TextNode(myobj, node, false);
   tmpNode16.isLeaf = true; 
   var myobj = { label: "sce_init", id: "sce_init", href: "sce_init.html", target:"basefrm" };
   var tmpNode17 = new YAHOO.widget.TextNode(myobj, node, false);
   tmpNode17.isLeaf = true; 
   var myobj = { label: "read_shufflepar", id: "read_shufflepar", href: "read_shufflepar.html", target:"basefrm" };
   var tmpNode18 = new YAHOO.widget.TextNode(myobj, node, false);
   tmpNode18.isLeaf = true; 
   var myobj = { label: "read_shufflevar", id: "read_shufflevar", href: "read_shufflevar.html", target:"basefrm" };
   var tmpNode19 = new YAHOO.widget.TextNode(myobj, node, false);
   tmpNode19.isLeaf = true; 
   var myobj = { label: "open_output", id: "open_output", href: "open_output.html", target:"basefrm" };
   var tmpNode20 = new YAHOO.widget.TextNode(myobj, node, false);
   tmpNode20.isLeaf = true; 
   var myobj = { label: "initialseed", id: "initialseed", href: "initialseed.html", target:"basefrm" };
   var tmpNode21 = new YAHOO.widget.TextNode(myobj, node, false);
   tmpNode21.isLeaf = true; 
   var myobj = { label: "ck_success", id: "ck_success", href: "ck_success.html", target:"basefrm" };
   var tmpNode22 = new YAHOO.widget.TextNode(myobj, node, false);
   tmpNode22.isLeaf = true; 
   var myobj = { label: "optsensitivity", id: "optsensitivity", href: "optsensitivity.html", target:"basefrm" };
   var tmpNode23 = new YAHOO.widget.TextNode(myobj, node, false);
   tmpNode23.isLeaf = true; 
   var myobj = { label: "run_cce", id: "run_cce", href: "run_cce.html", target:"basefrm" };
   var tmpNode24 = new YAHOO.widget.TextNode(myobj, node, false);
   tmpNode24.isLeaf = true; 
   var myobj = { label: "cce", id: "cce", href: "cce.html", target:"basefrm" };
   var tmpNode25 = new YAHOO.widget.TextNode(myobj, node, false);
   tmpNode25.isLeaf = true; 
   var myobj = { label: "simplex", id: "simplex", href: "simplex.html", target:"basefrm" };
   var tmpNode26 = new YAHOO.widget.TextNode(myobj, node, false);
   tmpNode26.isLeaf = true; 
   var myobj = { label: "runmodel", id: "runmodel", href: "runmodel.html", target:"basefrm" };
   var tmpNode27 = new YAHOO.widget.TextNode(myobj, node, false);
   tmpNode27.isLeaf = true; 
   var myobj = { label: "sortcomp", id: "sortcomp", href: "sortcomp.html", target:"basefrm" };
   var tmpNode28 = new YAHOO.widget.TextNode(myobj, node, false);
   tmpNode28.isLeaf = true; 
   var myobj = { label: "writeloop", id: "writeloop", href: "writeloop.html", target:"basefrm" };
   var tmpNode29 = new YAHOO.widget.TextNode(myobj, node, false);
   tmpNode29.isLeaf = true; 
   var myobj = { label: "writepars", id: "writepars", href: "writepars.html", target:"basefrm" };
   var tmpNode30 = new YAHOO.widget.TextNode(myobj, node, false);
   tmpNode30.isLeaf = true; 
   var myobj = { label: "write_lastbest", id: "write_lastbest", href: "write_lastbest.html", target:"basefrm" };
   var tmpNode31 = new YAHOO.widget.TextNode(myobj, node, false);
   tmpNode31.isLeaf = true; 
   var myobj = { label: "qsort", id: "qsort", href: "qsort.html", target:"basefrm" };
   var tmpNode32 = new YAHOO.widget.TextNode(myobj, node, false);
   tmpNode32.isLeaf = true; 
     // notify the TreeView component when data load is complete
     onCompleteCallback();
}
