#!/bin/sh

# the model-folder (look at computer_start.script for path)
CODEDIR=$(pwd)
# makes a result-folder inside your model-folder
STOREDIR=$CODEDIR/results
mkdir -p $STOREDIR
# copies all inside the result-folder
cp $CODEDIR/* $STOREDIR/
cd $STOREDIR
chmod u=rwx,g=rwx,o=r *
# starts vomrun.script as batch job until finalbest.txt is written
until test -e finalbest.txt; do
	$STOREDIR/computer_vomrun.script >> logfile.txt
done